"""Phase 4 e2e: TLS signaling.

Verifies that an INVITE arriving on tls:127.0.0.1:5061 is routed and
answered exactly like its UDP counterpart, using the self-signed cert
generated by the harness.
"""
from __future__ import annotations


def test_tls_invite_to_pbx1(sipp, uas_factory, tls_client_cert):
    """TLS UAC → Kamailio :5061 → UDP UAS on :5080."""
    cert, key = tls_client_cert
    uas_factory(5080)
    result = sipp.run(
        "uac_basic_call.xml",
        target="127.0.0.1:5061",
        local_ip="127.0.0.2",
        local_port=5090,
        calls=1,
        rate=1,
        timeout=30,
        service="1000",
        keys={"target_domain": "pbx1.local"},
        log_tag="tls_pbx1",
        transport="tls",
        tls_cert=cert,
        tls_key=key,
    )
    assert result.returncode == 0, (
        f"TLS UAC failed rc={result.returncode}\n{result.stdout}\n{result.stderr}"
    )


def test_tls_handshake_failure_on_udp_port(sipp, tls_client_cert):
    """TLS UAC pointed at the UDP port (5060) must fail to handshake.

    Sanity check: ensures TLS args are honoured and Kamailio's TLS port is
    actually different from the UDP one (i.e. SIPp doesn't transparently
    fall back to UDP).
    """
    cert, key = tls_client_cert
    result = sipp.run(
        "uac_basic_call.xml",
        target="127.0.0.1:5060",
        local_ip="127.0.0.2",
        local_port=5091,
        calls=1,
        rate=1,
        timeout=10,
        service="1000",
        keys={"target_domain": "pbx1.local"},
        log_tag="tls_handshake_fail",
        transport="tls",
        tls_cert=cert,
        tls_key=key,
    )
    assert result.returncode != 0, (
        "TLS UAC unexpectedly succeeded against the UDP port — TLS args "
        f"may be ignored.\n{result.stdout}\n{result.stderr}"
    )
